# Generated by Django 3.1.4 on 2020-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practapp', '0002_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
