# Generated by Django 3.1.4 on 2021-01-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practapp', '0013_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
