# Generated by Django 3.1.4 on 2021-01-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practapp', '0015_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cat',
        ),
    ]
