# Generated by Django 3.1.4 on 2021-01-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practapp', '0016_auto_20210104_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
