# Generated by Django 3.1.4 on 2021-01-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practapp', '0021_auto_20210104_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catogey',
        ),
        migrations.DeleteModel(
            name='Catogery',
        ),
    ]
